[package]
name = "ncontrol_plus"
version = "0.1.0"
edition = "2024"

[dependencies]
midir = "0.9"
tokio = { version = "1", features = ["full"] }
device_query = "1.1"
cocoa = "0.25"
objc = "0.2"
core-graphics = "0.22"
